services:
  database:
    image: postgres:16
    restart: always
    container_name: domino_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=domino_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: domino_backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    depends_on:
      - database

volumes:
  postgres_data:
