name: Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Copy .env.test for testing
        run: cp .env.test .env

      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: test

      # - name: Test coverage report
      #   run: npm run test:cov

      # - name: Upload coverage to GitHub
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: coverage-report
      #     path: coverage/
